#27/feat recipe regist firebase
jeonbyeongmin/yum pull request #30
Opened 2022-06-12 17:38 UTC by sumi-0011

이미지 업로드, 미리보기
레시피 DB에 등록

![image](https://user-images.githubusercontent.com/49177223/173245944-0c319c03-d43f-4d53-93b0-626082bf21a9.png)

2022-06-12 17:44 UTC, sumi-0011 commented
step image 렌더링이 한박자씩 느린데 어떻게 해결해야 할지 잘 모르겠어요 @jeonbyeongmin

2022-06-13 01:30 UTC, jeonbyeongmin requested changes
다음에는 작업하던 공간에서 브랜치 분기하지 말고 dev로 전환해서 dev에서 브랜치 분기해주시면 좋을것 같아요 ㅎㅎ.. 이 pr은 정확하게 어디 부분이 바뀐건가요?

2022-06-13 05:09 UTC, sumi-0011 commented
> 다음에는 작업하던 공간에서 브랜치 분기하지 말고 dev로 전환해서 dev에서 브랜치 분기해주시면 좋을것 같아요 ㅎㅎ.. 이 pr은 정확하게 어디 부분이 바뀐건가요?

이 브랜치는 dev에서 브랜치 분기한게 맞습니다!
레시피 등록 부분이 UI와 form control 만 구현되어있었는데, 
이미지 업로드와 이미지를 storage에 저장, 그리고 입력한 데이터를 firestore에 저장하는 부분까지 구현이 되었습니다. 
재료 부분은 스토어에서 가져와야 해서 아직 구현이 되지 않았어요

2022-06-13 06:34 UTC, jeonbyeongmin approved these changes

2022-06-13 06:35 UTC, merged